### ISSUE TITLE
Checkout Page

### ISSUE THREAD

**Issue by jodiely** [jodiely/Space-Shopper#11]
the submit button :
[X] clears req.cart - set to null
[X] updates order status to pending 
[X] update inventory qty 
[X] have the submit order button redirect to confirmation page
[X] make sure all fields are filled out before placing the order
[   ] IF no req.user (GUEST): create a user for guest
[   ] IF there IS req.user: find user and associate order to user

Maybe later:
- charge the user/integrate Stripe -- how?

**Comment by arinchoi03** [comment]
- send email to user email address
- redirect to 'Payment confirmed' page after submission is complete with order id?
